[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/book.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
